VotlisClothes/Controllers/CatalogueController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;
using VotlisClothes.Models;

namespace VotlisClothes.Controllers
{
    public class CatalogueController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Catalogue
        public async Task<ActionResult> Index()
        {
            var CollectionGroups = await db.CollectionGroups.ToListAsync();
            return View(CollectionGroups);
        }
        //
        // GET: /Catalogue/CollectionMenu
        [ChildActionOnly]
        public ActionResult CollectionMenu()
        {
            var collections = db.CollectionGroups.ToList();
            return PartialView(collections);
        }
        //
        // GET: /Catalogue/Browse?CollectionGroup=Summer2017
        public async Task<ActionResult> Browse(string CollectionName, string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.CollectionGroupSortParm = sortOrder == "CollectionGruop" ? "CollectionGruop_desc" : "CollectionGruop";
            ViewBag.SeasonSortParm = sortOrder == "Season" ? "Season_desc" : "Season";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "Price_desc" : "Price";
            ViewBag.QtySortParm = sortOrder == "Quantity" ? "Quantity_desc" : "Quantity";

            var getItems = new APIControllers.CatalogueController().GetItems(CollectionName,sortOrder, searchString);
            return View(await getItems.ToListAsync());
        }
        //
        // GET: /Catalogue/Details/1
        public  ActionResult Details(int id)
        {
            var getItem = new APIControllers.ItemsController().GetItem(id);
            var result = getItem as OkNegotiatedContentResult<Item>;
            return View( result.Content);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VotlisClothes/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;
using VotlisClothes.Models;

namespace VotlisClothes.Controllers
{
    [Authorize(Roles = "Employee")]
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Item
        public async Task<ActionResult> Index(string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.CollectionGroupSortParm = sortOrder == "CollectionGruop" ? "CollectionGruop_desc" : "CollectionGruop";
            ViewBag.SeasonSortParm = sortOrder == "Season" ? "Season_desc" : "Season";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "Price_desc" : "Price";
            ViewBag.QtySortParm = sortOrder == "Quantity" ? "Quantity_desc" : "Quantity";

            var getItems = new APIControllers.ItemsController().GetItems(sortOrder, searchString);
            return View(await getItems.ToListAsync());
        }

        // GET: Item/Details/5
        public ActionResult Details(int id)
        {
            var getItem = new APIControllers.ItemsController().GetItem(id);
            var result = getItem as OkNegotiatedContentResult<Item>;
            return View(result.Content);
        }

        // GET: Item/Create
        public ActionResult Create()
        {
            ViewBag.Seasons = new SelectList(db.Seasons, "Name", "Name");
            ViewBag.CollectionGroups = new SelectList(db.CollectionGroups, "Name", "Name");
            return View();
        }

        // POST: Item/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,CollectionGroup,Description,ImagePath,Color,Size,Price,Available,QuantityAvailable,SeasonId,HasDiscount,DiscountPercentage")] Item item)
        {
            var createItem = new APIControllers.ItemsController().PostItem(item);
            //var result = createItem as CreatedAtRouteNegotiatedContentResult<Item>;
            return RedirectToAction("Index");
        }

        // GET: Item/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.Seasons = new SelectList(db.Seasons, "Name", "Name");
            ViewBag.CollectionGroups = new SelectList(db.CollectionGroups, "Name", "Name");
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Item item = await db.Items.FindAsync(id);
            if (item == null)
                return HttpNotFound();
            return View(item);
        }

        // POST: Item/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,CollectionGroup,Description,ImagePath,Color,Size,Price,Available,QuantityAvailable,SeasonId,HasDiscount,DiscountPercentage")] Item item)
        {
            ViewBag.Seasons = new SelectList(db.Seasons, "Name", "Name");
            ViewBag.CollectionGroups = new SelectList(db.CollectionGroups, "Name", "Name");
            var editItem = new APIControllers.ItemsController().PutItem(item.Id,item);
            var result = editItem as OkNegotiatedContentResult<Item>;
            return View(result.Content);
        }

        // GET: Item/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Item item = await db.Items.FindAsync(id);
            if (item == null)
                return HttpNotFound();
            return View(item);
        }

        // POST: Item/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var deleteItem = new APIControllers.ItemsController().DeleteItem(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VotlisClothes/Views/Shared/_Layout.cshtml
@using VotlisClothes.Logic
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Catalogue
                        <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                           @{Html.RenderAction("CollectionMenu", "Catalogue");}
                        </ul>
                    </li>
                    @if (User.IsInRole("Employee")){ <li>@Html.ActionLink("Item Stock", "Index", "Items")</li>}
                    @if (User.IsInRole("Admin")){<li>@Html.ActionLink("Roles", "Index", "Role")</li>}
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @*@{Html.RenderAction("CollectionMenu", "Catalogue");}*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>