VotlisClothes/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VotlisClothes.Logic;
using VotlisClothes.Models;
using VotlisClothes.ViewModels;

namespace VotlisClothes.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        const string PromoCode = "VOLTIS";
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedItem = db.Items
                .Single(i => i.Id == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedItem);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string ItemName = db.Carts
                .Single(item => item.RecordId == id).Item.Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(ItemName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }

        //
        // GET: /Checkout/AddressAndPayment
        public ActionResult AddressAndPayment()
        {
            return View();
        }
        //
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new Order();
            TryUpdateModel(order);

            try
            {
                //if (string.Equals(values["PromoCode"], PromoCode,
                //    StringComparison.OrdinalIgnoreCase) == false)
                //{
                //    return View(order);
                //}
                //else
                //{
                    order.CustomerId = User.Identity.Name;
                    order.OrderDate = DateTime.Now;

                    //Process the order
                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    cart.CreateOrder(order);

                    return RedirectToAction("Complete",
                        new { id = order.Id });
                //}
            }
            catch(Exception ex)
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }
        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            //var TotalPrice = db.OrderItems.Where(oi => oi.Order_id == id).Sum(oi => oi.ItemPrice);
            // Validate customer owns this order
            bool isValid = db.Orders.Any(
                o => o.Id == id &&
                o.CustomerId == User.Identity.Name);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

VotlisClothes/Controllers/CatalogueController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;
using VotlisClothes.Models;

namespace VotlisClothes.Controllers
{
    public class CatalogueController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Catalogue
        public async Task<ActionResult> Index()
        {
            var CollectionGroups = await db.CollectionGroups.ToListAsync();
            return View(CollectionGroups);
        }
        //
        // GET: /Catalogue/CollectionMenu
        [ChildActionOnly]
        public ActionResult CollectionMenu()
        {
            var collections = db.CollectionGroups.ToList();
            return PartialView(collections);
        }
        //
        // GET: /Catalogue/Browse?CollectionGroup=Summer2017
        public async Task<ActionResult> Browse(string CollectionName, string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.CollectionGroupSortParm = sortOrder == "CollectionGruop" ? "CollectionGruop_desc" : "CollectionGruop";
            ViewBag.SeasonSortParm = sortOrder == "Season" ? "Season_desc" : "Season";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "Price_desc" : "Price";
            ViewBag.QtySortParm = sortOrder == "Quantity" ? "Quantity_desc" : "Quantity";

            var getItems = new APIControllers.CatalogueController().GetItems(CollectionName,sortOrder, searchString);
            return View(await getItems.ToListAsync());
        }
        //
        // GET: /Catalogue/Details/1
        public  ActionResult Details(int id)
        {
            var getItem = new APIControllers.ItemsController().GetItem(id);
            var result = getItem as OkNegotiatedContentResult<Item>;
            return View( result.Content);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VotlisClothes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VotlisClothes.Models;

namespace VotlisClothes.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public HomeController()
        {
        }
        public ActionResult Index()
        {
            ViewBag.CollectionGroups = new SelectList(db.CollectionGroups, "Name", "Name");

            IEnumerable<Item> items = db.Items.OrderBy(i=>i.Name).ToList();
            return View(items);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VotlisClothes/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VotlisClothes/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VotlisClothes/Views/Home/Index.cshtml
@model IEnumerable<VotlisClothes.Models.Item>
@{
    ViewBag.Title = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/Pictures/banner8.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Browse our new belt collection here.
                    @Html.ActionLink("Belts", "Browse","Catalogue", new { sortOrder = ViewBag.CollectionGroupSortParm, CollectionName = Model.First().CollectionGroup },new { @class ="btn btn-default"})
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/Pictures/banner12.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Browse our new jeans collection here.
                    @Html.ActionLink("Jeans", "Browse", "Catalogue", new { sortOrder = ViewBag.CollectionGroupSortParm, CollectionName = Model.Last().CollectionGroup }, new { @class = "btn btn-default" })
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/Pictures/banner2m.jpg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Browse our latest collectios here.
                    @Html.ActionLink("Collections", "Index", "Catalogue", null, new { @class = "btn btn-default" })
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/Pictures/banner7.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Browse our latest collectios here.
                    @Html.ActionLink("Collections", "Index", "Catalogue",null, new { @class = "btn btn-default" })
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<h3 style="text-align: center;"><em> Clothing and Fashion </em></h3>
<div class="col-xs-12 col-md-12">
    <div class="row">
        @foreach (var item in Model)
            {
            <div class="col-xs-12 col-md-3">
                <div class="thumbnail">
                    <img src="@item.ImagePath" height="140" width="140">
                    <div class="caption text-center">
                        <p>
                            <b>Name:</b> <span>@item.Name</span>
                        </p>
                        <p>
                            <b>Price:</b> <span>@item.Price Euro</span>
                        </p>
                        <p class="text-center">
                            @Html.ActionLink("Details", "Details", "Catalogue", new { id = item.Id }, new { @class = "btn btn-info" }) 
                            @Html.ActionLink("Add to cart", "AddToCart", "Cart", new { id = item.Id }, new { @class = "btn btn-info" })
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>